"""
Django settings for xys project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from configparser import RawConfigParser
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

try:
    config = RawConfigParser()
    config.read('/etc/django_settings.ini')
    SECRET_KEY = config.get('production', 'SECRET_KEY')
except KeyError as e:
    raise RuntimeError("Could not find a SECRET_KEY in environment") from e

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['csms.deltaearthmoving.com', 'localhost', '127.0.0.1', '192.168.88.88', '61.245.4.14']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

     # UNCOMMENT THESE APPS AFTER FIRST RUN
    'base.apps.BaseConfig',
    'comment.apps.CommentConfig',
    'document.apps.DocumentConfig',

    # 'project.apps.ProjectConfig',
    # 'inventory.apps.InventoryConfig',
    # 'cit.apps.CitConfig',

    # 'scrum.apps.ScrumConfig',
    
    'import_export',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_filters',                 
    'django_tables2',               
    'django_select2',
    'django_password_eye'
    # -------------------------------
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_currentuser.middleware.ThreadLocalUserMiddleware',
]

ROOT_URLCONF = 'xys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    ("admin", os.path.join(BASE_DIR, 'static/admin')),
    ("niceadmin", os.path.join(BASE_DIR, 'static/niceadmin')),
    ("img", os.path.join(BASE_DIR, 'static/img')),
    ("css", os.path.join(BASE_DIR, 'static/css')),
    ("js", os.path.join(BASE_DIR, 'static/js')),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

FIXTURE_DIRS = [
    os.path.join(BASE_DIR, 'fixtures'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # One month

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = ['https://csms.deltaearthmoving.com']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# CUSTOMIZED ICONS
PLEDGE_ICON = 'bi bi-people'
PLEDGE_CARD_ICON = 'bi bi-person-vcard'
PLEDGE_ADD_ICON = 'bi bi-person-plus me-1'
PLEDGE_TYPES_ICON = 'bi bi-heart-pulse'
PLEDGE_AMOUNT_ICON = 'bi bi-heart-pulse-fill'
CONTRIBUTION_ICON = 'bi bi-cash-stack'
CONTRIBUTION_ADD_ICON = 'bi bi-cash-coin'
REPORT_ICON = 'bi bi-file-bar-graph'


CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

SELECT2_THEME = 'bootstrap-5'
SELECT2_I18N_PATH = 'admin/jsi18n/'

DELETE_DOCUMENTS_FROM_DISK = True
FILE_UPLOAD_MAX_SIZE = 5 * 1024 * 1024  # in megabytes
FILE_UPLOAD_ALLOWED_TYPES = ['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'xls', 'xlsx']

TIME_INPUT_FORMATS = ('%H:%M',)

# AUTH_USER_MODEL = 'base.CustomUser'
